### ISSUE TITLE
strange Warning durning init

### ISSUE THREAD

**Issue by konstantin-schekotihin** [gaste/dwasp-gui#2]
File  - open project, results in the following warning:

WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0
x80000002. Windows RegCreateKeyEx(...) returned error code 5.

run on windows 8.1, java 8 update 60

**Comment by gaste** [comment]
The [Java Preferences API](https://docs.oracle.com/javase/8/docs/technotes/guides/preferences/overview.html) is used to store the user setttings. The Windows implementation of this API is using the registry as storage for the preferences. Unfortionately, the API tries to access the system of the registry during the initialization (even if it is not needed), which requires administrator privileges (see [this stackoverflow answer](http://stackoverflow.com/a/18834971/2623126)). There is a bug report ([JDK-6809488](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6809488)) issued, but it does not look like it will get fixed.

The warning messages from the Preferences API logging cannot be disabled programatically. Thus a possible resolution of this issue is store the user settings in a perferences file, i.e. `${user.home}/.dwasp-gui/settings.properties`.

**Comment by gaste** [comment]
Changed the implementation to use a properties file (see 3ed892c).
